
/* Drop Indexes */

DROP INDEX IF EXISTS UIDX_ABSENCE_BEHAVIOR_INFO;
DROP INDEX IF EXISTS UIDX_ACCOUNT_INFO;
DROP INDEX IF EXISTS UIDX_CALL_REGULATION_INFO;
DROP INDEX IF EXISTS UIDX_EXTENSION_NUMBER_INFO;
DROP INDEX IF EXISTS UIDX_INCOMING_GROUP_INFO;
DROP INDEX IF EXISTS UIDX_N_NUMBER_INFO;
DROP INDEX IF EXISTS UIDX_OUTSIDE_CALL_INCOMING_INFO;
DROP INDEX IF EXISTS UIDX_OUTSIDE_CALL_SENDING_INFO;
DROP INDEX IF EXISTS UIDX_VM_INFO_1;
DROP INDEX IF EXISTS UIDX_VM_INFO_2;
DROP INDEX IF EXISTS UIDX_VM_INFO_3;
DROP INDEX IF EXISTS UIDX_VM_INFO_4;
DROP INDEX IF EXISTS UIDX_VM_INFO_5;


/* Create Indexes */

CREATE UNIQUE INDEX UIDX_ABSENCE_BEHAVIOR_INFO ON ABSENCE_BEHAVIOR_INFO (EXTENSION_NUMBER_INFO_ID) WHERE NOT delete_flag;
CREATE UNIQUE INDEX UIDX_ACCOUNT_INFO ON ACCOUNT_INFO (LOGIN_ID) WHERE NOT delete_flag;
CREATE UNIQUE INDEX UIDX_CALL_REGULATION_INFO ON CALL_REGULATION_INFO (N_NUMBER_INFO_ID) WHERE NOT delete_flag;
CREATE UNIQUE INDEX UIDX_EXTENSION_NUMBER_INFO ON EXTENSION_NUMBER_INFO (TERMINAL_MAC_ADDRESS) WHERE NOT delete_flag;
CREATE UNIQUE INDEX UIDX_INCOMING_GROUP_INFO ON INCOMING_GROUP_INFO (EXTENSION_NUMBER_INFO_ID) WHERE NOT delete_flag;
CREATE UNIQUE INDEX UIDX_N_NUMBER_INFO ON N_NUMBER_INFO (N_NUMBER_NAME) WHERE NOT delete_flag;
CREATE UNIQUE INDEX UIDX_OUTSIDE_CALL_INCOMING_INFO ON OUTSIDE_CALL_INCOMING_INFO (OUTSIDE_CALL_INFO_ID) WHERE NOT delete_flag;
CREATE UNIQUE INDEX UIDX_OUTSIDE_CALL_SENDING_INFO ON OUTSIDE_CALL_SENDING_INFO (EXTENSION_NUMBER_INFO_ID) WHERE NOT delete_flag;
CREATE UNIQUE INDEX UIDX_VM_INFO_1 ON VM_INFO (VM_ID) WHERE NOT delete_flag;
CREATE UNIQUE INDEX UIDX_VM_INFO_2 ON VM_INFO (VM_PRIVATE_IP_B) WHERE NOT delete_flag;
CREATE UNIQUE INDEX UIDX_VM_INFO_3 ON VM_INFO (FQDN) WHERE NOT delete_flag;
CREATE UNIQUE INDEX UIDX_VM_INFO_4 ON VM_INFO (VPN_GLOBAL_IP) WHERE NOT delete_flag;
CREATE UNIQUE INDEX UIDX_VM_INFO_5 ON VM_INFO (VPN_PRIVATE_IP) WHERE NOT delete_flag;

